### ISSUE TITLE
Not showing icons

### ISSUE THREAD

**Issue by MohamedIrfanAM** [cdump/ranger-devicons2#2]
I have nerd fonts `FantasqueSansMono Nerd Font Mono 9.6` in my terminal.

cloned 
`git clone https://github.com/cdump/ranger-devicons2 ~/.config/ranger/plugins/devicons2`
 added this in my rc.conf
`default_linemode devicons2`

I have installed vim-divisions in Neovim and it is working perfectly fine.
Anything wrong with my config ??
Please help

**Comment by MohamedIrfanAM** [comment]
It was an issue with locale, now i fixed it :)

**Comment by p1k0pan** [comment]
Can you explain how to fix it please? Now I have the same issue.

> It was an issue with locale, now i fixed it :)
