### ISSUE TITLE
devicons2 does not display

### ISSUE THREAD

**Issue by p1k0pan** [cdump/ranger-devicons2#4]
## Runtime Environment
Operating system and version: archlinux 5.13.9
Terminal emulator and version: st 0.8.2
Python version: 3.9.6
Ranger version/commit: 1.9.3
Locale: None.None

## Current Behavior
I have followed the guide from devicons2 ,
1. clone the repo to .config/ranger/plugins
2. add the script in my rc.conf
3. install nerd-font (sauce code pro nerd font)
4. change my st terminal default font to nerd font ( I have even changed my system default font)

## Expected Behavior
my ranger should show devicons after I follow the guide completely

**Comment by cdump** [comment]
Do you compile st from sources? Can you show your `config.h` (especially `static char *font` and post screenshot?

I've tried [vanilla st from aur ](https://aur.archlinux.org/packages/st/), [LukeSmithxyz's version](https://github.com/LukeSmithxyz/st) and [vanilla verison from suckless](https://st.suckless.org/) compiled with make, and every version works fine for me.
You can also try to run `fc-cache -v` to update your fonts cache and `fc-match 'your-font-name-from-config-h'` to check is font installed without errors


p.s. I'm using `static char *font = "DejaVuSansMono Nerd Font Mono:pixelsize=18";` in my config

**Comment by p1k0pan** [comment]
I took your advice and change my fonts setting in st and it works finally.
Thanks you so much
