### ISSUE TITLE
Permission denied: '//home/gfzum/.config/ranger/plugins/__init__.py'

### ISSUE THREAD

**Issue by gfzum** [cdump/ranger-devicons2#5]
After git clone the package, when I ran ranger in the terminal it showed:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 122, in main
    load_settings(fm, args.clean)
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 448, in load_settings
    with open(
PermissionError: [Errno 13] Permission denied: '/home/gfzum/.config/ranger/plugins/__init__.py'
```

I've added `default_linemode devicons2` in `~/.config/ranger/rc.conf` and my terminal font is Noto Mono
I've also tried `chmod u+w -R ~/.config/ranger` but it didn't work.

**Comment by Tracygolden** [comment]
Same problem on Arch with commits using new install method(later than https://github.com/alexanderjeurissen/ranger_devicons/commit/f0b8fc241407249ed0aeaa1161eaf6c2da9653fb):
Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime

Moving *.py files to the root of the plugins directory solves the problem:
mv -fv ~/.config/ranger/plugins/ranger_devicons/*.py ~/.config/ranger/plugins #Works fine now

**Comment by cdump** [comment]
If it's still actual on master branch, please reopen the issue
