### ISSUE TITLE
vue icon doesn't show up

### ISSUE THREAD

**Issue by Rogerskelamen** [cdump/ranger-devicons2#7]
<img width="1057" alt="截屏2022-11-18 21 20 22" src="https://user-images.githubusercontent.com/58795886/202714508-9022607e-c2ab-44a4-ab27-ead0449247dd.png">
just like above, no vue icon appearing with vue file.

my machine: MacBook Air M1

I wonder what's going wrong with it, thanks if someone can help me here.

**Comment by cdump** [comment]
@Rogerskelamen is it still broken?

**Comment by Rogerskelamen** [comment]
<img width="1178" alt="截屏2024-03-04 10 11 11" src="https://github.com/cdump/ranger-devicons2/assets/58795886/69e46767-d8c2-453e-83dc-7d2f9125407d">
It looks like normal now (though I may get broken in my fonts)
